/** TESTS NOT NEEDED **/

//created on: Apr 7, 2014
package cz.muni.fi.civ.newohybat.drools.rules

//list any import classes here.
import cz.muni.fi.civ.newohybat.persistence.facade.dto.*;
import cz.muni.fi.civ.newohybat.persistence.facade.dto.UnitDTO;
import cz.muni.fi.civ.newohybat.persistence.facade.dto.TileDTO;

import org.kie.api.runtime.process.WorkflowProcessInstance;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import java.util.ArrayList;
import org.kie.api.runtime.process.ProcessInstance;

import cz.muni.fi.civ.newohybat.drools.events.TileImprovementEvent;
import cz.muni.fi.civ.newohybat.drools.events.CityImprovementEvent;
import cz.muni.fi.civ.newohybat.drools.events.TurnEvent;
import cz.muni.fi.civ.newohybat.drools.events.UnitEvent;
import cz.muni.fi.civ.newohybat.drools.events.CityEvent;
import cz.muni.fi.civ.newohybat.drools.events.AdvanceEvent;
import cz.muni.fi.civ.newohybat.drools.events.MoveEvent;

//declare any global variables here

declare Fight
	attacker:UnitDTO
	defender:UnitDTO
end
declare FightProposal
	attacker:UnitDTO
	defender:UnitDTO
end
declare UnitIdle
	unit:UnitDTO
end
declare UnitAlive
	unit:UnitDTO
end
declare UnitDead
	unit:UnitDTO
	cause:Fight
end
declare UnitBusy
	unit:UnitDTO
	action:WorkflowProcessInstance
end
declare TurnEvent
	@role(event)
end
declare ProcessWaitsForTurnEvent
	@role(event)
	processId:Long
end

declare TileImprovementEvent
	@role(event)
end

declare UnitEvent
	@role( event )
	//@expires( 1ms )
end

declare AdvanceEvent
	@role( event )
end
declare CityImprovementEvent
	@role( event )
end
declare UpdateCityProduction
	cityId:Long
end
declare UpdateUnitsSupport
	cityId:Long
end
declare UpdateFoodConsumption
	cityId:Long
end

declare CityImprovementChange
	cityId:Long
end

declare TileImprovementChange
	tileId:Long
end

declare UpdateEnabledImprovementsRequest
	playerId:Long
end

declare UpdateUnitActionsRequest
	unitId:Long
end

declare AdvanceReached
	playerId:Long
end

declare WonderBuilt
	ident:String
end
declare MovementPlan
	unit:Long
	start:TileDTO
	target:TileDTO
	path:ArrayList
end
